version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./api
    depends_on:
      - db
    ports:
      - "3000:3000"

  flutter-app:
    build: .
    depends_on:
      - api
    ports:
      - "8080:80"

volumes:
  db-data: